
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUnwEf4IyY-oKx-lNfxM4vbT12EU2SVNs',
    appId: '1:517379302378:web:1511d56877a1c78f514893',
    messagingSenderId: '517379302378',
    projectId: 'chat-app-900bf',
    authDomain: 'chat-app-900bf.firebaseapp.com',
    storageBucket: 'chat-app-900bf.appspot.com',
    measurementId: 'G-VF12SS8K2D',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ7xDDmRjY_BZex67tUxgf8lur1V0uVU4',
    appId: '1:517379302378:ios:90f861dc4e5a23e4514893',
    messagingSenderId: '517379302378',
    projectId: 'chat-app-900bf',
    storageBucket: 'chat-app-900bf.appspot.com',
    iosClientId: '517379302378-jjfloe6iu47kcruk4jkrnod8g7tethi2.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ7xDDmRjY_BZex67tUxgf8lur1V0uVU4',
    appId: '1:517379302378:ios:90f861dc4e5a23e4514893',
    messagingSenderId: '517379302378',
    projectId: 'chat-app-900bf',
    storageBucket: 'chat-app-900bf.appspot.com',
    iosClientId: '517379302378-jjfloe6iu47kcruk4jkrnod8g7tethi2.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
